#import <Foundation/Foundation.h>

typedef NS_ENUM(NSUInteger, XLOGGER_TYPE) {
    XLOGGER_TYPE_NSLOG_REPLACEMENT = 0,
    XLOGGER_TYPE_DEBUG = 1,
    XLOGGER_TYPE_DEVELOPMENT = 2,
    XLOGGER_TYPE_DEBUG_DEVELOPMENT = 3,
    XLOGGER_TYPE_ONLINE_SERVICES = 4,
    XLOGGER_TYPE_ALL = 5
};

typedef NS_ENUM(NSUInteger, XLOGGER_LEVEL) {
    XLOGGER_LEVEL_SIMPLE = 10,
    XLOGGER_LEVEL_SIMPLE_NO_HEADER = 11,
    XLOGGER_LEVEL_INFORMATION = 12,
    XLOGGER_LEVEL_IMPORTANT = 13,
    XLOGGER_LEVEL_WARNING = 14,
    XLOGGER_LEVEL_ERROR = 15,
    XLOGGER_LEVEL_ALL = 16
};

typedef NS_ENUM(NSUInteger, XLOGGER_ARGS) {
    XLOGGER_ARGS_LOG_DESCRIPTION = 100,
    XLOGGER_ARGS_TIMESTAMP = 101,
    XLOGGER_ARGS_CALLEE = 102,
    XLOGGER_ARGS_CALLEE_METHOD = 103,
    XLOGGER_ARGS_LINE_NUMBER = 104,
    XLOGGER_ARGS_FILE_NAME = 105
};

#define XL_LEVEL_SIMPLE           @(XLOGGER_LEVEL_SIMPLE)
#define XL_LEVEL_SIMPLE_NO_HEADER @(XLOGGER_LEVEL_SIMPLE_NO_HEADER)
#define XL_LEVEL_INFORMATION      @(XLOGGER_LEVEL_INFORMATION)
#define XL_LEVEL_IMPORTANT        @(XLOGGER_LEVEL_IMPORTANT)
#define XL_LEVEL_WARNING          @(XLOGGER_LEVEL_WARNING)
#define XL_LEVEL_ERROR            @(XLOGGER_LEVEL_ERROR)

#define XL_ARG_LOG_DESCRIPTION @(XLOGGER_ARGS_LOG_DESCRIPTION)
#define XL_ARG_TIMESTAMP       @(XLOGGER_ARGS_TIMESTAMP)
#define XL_ARG_CALLEE_ADDRESS  @(XLOGGER_ARGS_CALLEE)
#define XL_ARG_CALLEE_METHOD   @(XLOGGER_ARGS_CALLEE_METHOD)
#define XL_ARG_LINE_NUMBER     @(XLOGGER_ARGS_LINE_NUMBER)
#define XL_ARG_FILE_NAME       @(XLOGGER_ARGS_FILE_NAME)

#define XL_LOG_MESSAGE(_type, _level, input, ...) \
[[XcodeLogger sharedManager] emitCompatibilityLogWithType:(_type) \
                                                    level:(_level) \
                                                     file:[NSString stringWithUTF8String:__FILE__] \
                                                 function:[NSString stringWithUTF8String:__PRETTY_FUNCTION__] \
                                                     line:__LINE__ \
                                                  message:[NSString stringWithFormat:(input), ##__VA_ARGS__] \
                                                 metadata:@{}]

#define XLog(input, ...)           XL_LOG_MESSAGE(XLOGGER_TYPE_NSLOG_REPLACEMENT, XLOGGER_LEVEL_SIMPLE, input, ##__VA_ARGS__)
#define XLog_NH(input, ...)        XL_LOG_MESSAGE(XLOGGER_TYPE_NSLOG_REPLACEMENT, XLOGGER_LEVEL_SIMPLE_NO_HEADER, input, ##__VA_ARGS__)
#define XLog_INFO(input, ...)      XL_LOG_MESSAGE(XLOGGER_TYPE_NSLOG_REPLACEMENT, XLOGGER_LEVEL_INFORMATION, input, ##__VA_ARGS__)
#define XLog_IMPORTANT(input, ...) XL_LOG_MESSAGE(XLOGGER_TYPE_NSLOG_REPLACEMENT, XLOGGER_LEVEL_IMPORTANT, input, ##__VA_ARGS__)
#define XLog_WARNING(input, ...)   XL_LOG_MESSAGE(XLOGGER_TYPE_NSLOG_REPLACEMENT, XLOGGER_LEVEL_WARNING, input, ##__VA_ARGS__)
#define XLog_ERROR(input, ...)     XL_LOG_MESSAGE(XLOGGER_TYPE_NSLOG_REPLACEMENT, XLOGGER_LEVEL_ERROR, input, ##__VA_ARGS__)

#define DLog(input, ...)           XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG, XLOGGER_LEVEL_SIMPLE, input, ##__VA_ARGS__)
#define DLog_NH(input, ...)        XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG, XLOGGER_LEVEL_SIMPLE_NO_HEADER, input, ##__VA_ARGS__)
#define DLog_INFO(input, ...)      XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG, XLOGGER_LEVEL_INFORMATION, input, ##__VA_ARGS__)
#define DLog_IMPORTANT(input, ...) XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG, XLOGGER_LEVEL_IMPORTANT, input, ##__VA_ARGS__)
#define DLog_WARNING(input, ...)   XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG, XLOGGER_LEVEL_WARNING, input, ##__VA_ARGS__)
#define DLog_ERROR(input, ...)     XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG, XLOGGER_LEVEL_ERROR, input, ##__VA_ARGS__)

#define DVLog(input, ...)           XL_LOG_MESSAGE(XLOGGER_TYPE_DEVELOPMENT, XLOGGER_LEVEL_SIMPLE, input, ##__VA_ARGS__)
#define DVLog_NH(input, ...)        XL_LOG_MESSAGE(XLOGGER_TYPE_DEVELOPMENT, XLOGGER_LEVEL_SIMPLE_NO_HEADER, input, ##__VA_ARGS__)
#define DVLog_INFO(input, ...)      XL_LOG_MESSAGE(XLOGGER_TYPE_DEVELOPMENT, XLOGGER_LEVEL_INFORMATION, input, ##__VA_ARGS__)
#define DVLog_IMPORTANT(input, ...) XL_LOG_MESSAGE(XLOGGER_TYPE_DEVELOPMENT, XLOGGER_LEVEL_IMPORTANT, input, ##__VA_ARGS__)
#define DVLog_WARNING(input, ...)   XL_LOG_MESSAGE(XLOGGER_TYPE_DEVELOPMENT, XLOGGER_LEVEL_WARNING, input, ##__VA_ARGS__)
#define DVLog_ERROR(input, ...)     XL_LOG_MESSAGE(XLOGGER_TYPE_DEVELOPMENT, XLOGGER_LEVEL_ERROR, input, ##__VA_ARGS__)

#define DDLog(input, ...)           XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG_DEVELOPMENT, XLOGGER_LEVEL_SIMPLE, input, ##__VA_ARGS__)
#define DDLog_NH(input, ...)        XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG_DEVELOPMENT, XLOGGER_LEVEL_SIMPLE_NO_HEADER, input, ##__VA_ARGS__)
#define DDLog_INFO(input, ...)      XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG_DEVELOPMENT, XLOGGER_LEVEL_INFORMATION, input, ##__VA_ARGS__)
#define DDLog_IMPORTANT(input, ...) XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG_DEVELOPMENT, XLOGGER_LEVEL_IMPORTANT, input, ##__VA_ARGS__)
#define DDLog_WARNING(input, ...)   XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG_DEVELOPMENT, XLOGGER_LEVEL_WARNING, input, ##__VA_ARGS__)
#define DDLog_ERROR(input, ...)     XL_LOG_MESSAGE(XLOGGER_TYPE_DEBUG_DEVELOPMENT, XLOGGER_LEVEL_ERROR, input, ##__VA_ARGS__)

#define OLog(input, ...)           XL_LOG_MESSAGE(XLOGGER_TYPE_ONLINE_SERVICES, XLOGGER_LEVEL_SIMPLE, input, ##__VA_ARGS__)
#define OLog_NH(input, ...)        XL_LOG_MESSAGE(XLOGGER_TYPE_ONLINE_SERVICES, XLOGGER_LEVEL_SIMPLE_NO_HEADER, input, ##__VA_ARGS__)
#define OLog_INFO(input, ...)      XL_LOG_MESSAGE(XLOGGER_TYPE_ONLINE_SERVICES, XLOGGER_LEVEL_INFORMATION, input, ##__VA_ARGS__)
#define OLog_IMPORTANT(input, ...) XL_LOG_MESSAGE(XLOGGER_TYPE_ONLINE_SERVICES, XLOGGER_LEVEL_IMPORTANT, input, ##__VA_ARGS__)
#define OLog_WARNING(input, ...)   XL_LOG_MESSAGE(XLOGGER_TYPE_ONLINE_SERVICES, XLOGGER_LEVEL_WARNING, input, ##__VA_ARGS__)
#define OLog_ERROR(input, ...)     XL_LOG_MESSAGE(XLOGGER_TYPE_ONLINE_SERVICES, XLOGGER_LEVEL_ERROR, input, ##__VA_ARGS__)
